### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MisterXtreme** [RevDevGames/eden#1]
This is a roadmap for Eden, it is highly subject to change. Discussion should take place below.

## Outline
- [x] Required mapgen nodes & textures: Done
- [x] Basic Trees
- [x] Ores (iron, diamond, gold, etc)
- [ ] Crafting (guide, custom system (?), etc...)
- [ ] Achievement system: WIP
- [ ] Basic game functionality, i.e. furnaces, anvil, tools: WIP
- [ ] NPCs and mobs
- [ ] Structure generation
- [ ] Quests
- [ ] Wider range of biomes
- [ ] Custom Caves

## Tools
- [x] Tool registration API
- [ ] Tool repair
- [ ] Tool upgrade system
- [ ] Rock (Pickaxe, axe, shovel, hoe, sword): Missing stone for craft
- [ ] Stone
- [x] Steel
- [ ] Gold
- [ ] Diamond

## Trees
- [ ] Add leaf-decay mechanism
- [x] API
- [x] Oak
- [ ] Acacia
- [ ] Birch
- [ ] Pine
- [ ] Palm
- [x] Lupuna

## Biomes
- [x] Grassland
- [ ] Swamp
- [ ] Ocean/Beach
- [ ] High Mountains
- [ ] Desert
- [ ] Savana
- [ ] Jungle/Rainforest: Incomplete
- [ ] Stone (like Extreme Hills from MC)

## Mapgen Materials
- [ ] Gravel
- [ ] Rocks (nodebox/model)
- [ ] Limestone (?)
- [ ] Granite (?)

**Comment by octacian** [comment]
* A rock toolset has been added, but with knives, hatchets, and spades rather than swords, axes, and shovels. The slightly different tools require only 1 stick rather than 2 to craft. They currently use cobblestone as rocks are not complete.
* The Lupuna tree has been implemented in the Jungle biome, which is very incomplete.

I'd personally like to add at least one bush for each biome, and although I could just make a simplified schematic using oak and lupuna tree nodes, I'd prefer something a bit more special.
